// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/add_transaction/data_layer/model/transaction_model.dart';
import 'features/category/data_layer/model/category_model.dart';
import 'features/ledger/data_layer/models/ledger_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 4324871529000987744),
      name: 'TransactionModel',
      lastPropertyId: const obx_int.IdUid(6, 5019323555561638200),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 8152111216725888197),
            name: 'id',
            type: 6,
            flags: 129),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 8484837863198934642),
            name: 'amount',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 948439506825432572),
            name: 'date',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 8198935935424583420),
            name: 'categoryFrom',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 2583205664040630386),
            name: 'categoryTo',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 5019323555561638200),
            name: 'type',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(4, 2569232988467431518),
      name: 'CategoryModel',
      lastPropertyId: const obx_int.IdUid(4, 8923997284882049744),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 2105827177741568055),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 3697390202441574555),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 6603503807476978370),
            name: 'slug',
            type: 9,
            flags: 2080,
            indexId: const obx_int.IdUid(3, 4714854442517657664)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 8923997284882049744),
            name: 'isDefault',
            type: 1,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(5, 6798321023293377370),
      name: 'LedgerModel',
      lastPropertyId: const obx_int.IdUid(5, 8556637126393128510),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 2581745766984483622),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 9059871112021056845),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 5016222731181500917),
            name: 'categoryType',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 1463524144725750414),
            name: 'openingBalance',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 8556637126393128510),
            name: 'openingBalanceType',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(5, 6798321023293377370),
      lastIndexId: const obx_int.IdUid(3, 4714854442517657664),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [6114446958660389306, 4236097693042086683],
      retiredIndexUids: const [],
      retiredPropertyUids: const [
        3375736797520531700,
        2965707209796176605,
        2190376645185791078,
        8672615465892326974,
        3915780905291677177,
        3774170466218628783,
        6640190761632438989
      ],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    TransactionModel: obx_int.EntityDefinition<TransactionModel>(
        model: _entities[0],
        toOneRelations: (TransactionModel object) => [],
        toManyRelations: (TransactionModel object) => {},
        getId: (TransactionModel object) => object.id,
        setId: (TransactionModel object, int id) {
          object.id = id;
        },
        objectToFB: (TransactionModel object, fb.Builder fbb) {
          final amountOffset = fbb.writeString(object.amount);
          final dateOffset = fbb.writeString(object.date);
          final categoryFromOffset = fbb.writeString(object.categoryFrom);
          final categoryToOffset = fbb.writeString(object.categoryTo);
          final typeOffset = fbb.writeString(object.type);
          fbb.startTable(7);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, amountOffset);
          fbb.addOffset(2, dateOffset);
          fbb.addOffset(3, categoryFromOffset);
          fbb.addOffset(4, categoryToOffset);
          fbb.addOffset(5, typeOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final amountParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final dateParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final categoryFromParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, '');
          final categoryToParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 12, '');
          final typeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 14, '');
          final object = TransactionModel(
              id: idParam,
              amount: amountParam,
              date: dateParam,
              categoryFrom: categoryFromParam,
              categoryTo: categoryToParam,
              type: typeParam);

          return object;
        }),
    CategoryModel: obx_int.EntityDefinition<CategoryModel>(
        model: _entities[1],
        toOneRelations: (CategoryModel object) => [],
        toManyRelations: (CategoryModel object) => {},
        getId: (CategoryModel object) => object.id,
        setId: (CategoryModel object, int id) {
          object.id = id;
        },
        objectToFB: (CategoryModel object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          final slugOffset = fbb.writeString(object.slug);
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addOffset(2, slugOffset);
          fbb.addBool(3, object.isDefault);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final slugParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final isDefaultParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 10, false);
          final object = CategoryModel(
              id: idParam,
              name: nameParam,
              slug: slugParam,
              isDefault: isDefaultParam);

          return object;
        }),
    LedgerModel: obx_int.EntityDefinition<LedgerModel>(
        model: _entities[2],
        toOneRelations: (LedgerModel object) => [],
        toManyRelations: (LedgerModel object) => {},
        getId: (LedgerModel object) => object.id,
        setId: (LedgerModel object, int id) {
          object.id = id;
        },
        objectToFB: (LedgerModel object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          final categoryTypeOffset = fbb.writeString(object.categoryType);
          final openingBalanceTypeOffset =
              fbb.writeString(object.openingBalanceType);
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addOffset(2, categoryTypeOffset);
          fbb.addInt64(3, object.openingBalance);
          fbb.addOffset(4, openingBalanceTypeOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final categoryTypeParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, '');
          final openingBalanceParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final openingBalanceTypeParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 12, '');
          final object = LedgerModel(
              id: idParam,
              name: nameParam,
              categoryType: categoryTypeParam,
              openingBalance: openingBalanceParam,
              openingBalanceType: openingBalanceTypeParam);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [TransactionModel] entity fields to define ObjectBox queries.
class TransactionModel_ {
  /// See [TransactionModel.id].
  static final id =
      obx.QueryIntegerProperty<TransactionModel>(_entities[0].properties[0]);

  /// See [TransactionModel.amount].
  static final amount =
      obx.QueryStringProperty<TransactionModel>(_entities[0].properties[1]);

  /// See [TransactionModel.date].
  static final date =
      obx.QueryStringProperty<TransactionModel>(_entities[0].properties[2]);

  /// See [TransactionModel.categoryFrom].
  static final categoryFrom =
      obx.QueryStringProperty<TransactionModel>(_entities[0].properties[3]);

  /// See [TransactionModel.categoryTo].
  static final categoryTo =
      obx.QueryStringProperty<TransactionModel>(_entities[0].properties[4]);

  /// See [TransactionModel.type].
  static final type =
      obx.QueryStringProperty<TransactionModel>(_entities[0].properties[5]);
}

/// [CategoryModel] entity fields to define ObjectBox queries.
class CategoryModel_ {
  /// See [CategoryModel.id].
  static final id =
      obx.QueryIntegerProperty<CategoryModel>(_entities[1].properties[0]);

  /// See [CategoryModel.name].
  static final name =
      obx.QueryStringProperty<CategoryModel>(_entities[1].properties[1]);

  /// See [CategoryModel.slug].
  static final slug =
      obx.QueryStringProperty<CategoryModel>(_entities[1].properties[2]);

  /// See [CategoryModel.isDefault].
  static final isDefault =
      obx.QueryBooleanProperty<CategoryModel>(_entities[1].properties[3]);
}

/// [LedgerModel] entity fields to define ObjectBox queries.
class LedgerModel_ {
  /// See [LedgerModel.id].
  static final id =
      obx.QueryIntegerProperty<LedgerModel>(_entities[2].properties[0]);

  /// See [LedgerModel.name].
  static final name =
      obx.QueryStringProperty<LedgerModel>(_entities[2].properties[1]);

  /// See [LedgerModel.categoryType].
  static final categoryType =
      obx.QueryStringProperty<LedgerModel>(_entities[2].properties[2]);

  /// See [LedgerModel.openingBalance].
  static final openingBalance =
      obx.QueryIntegerProperty<LedgerModel>(_entities[2].properties[3]);

  /// See [LedgerModel.openingBalanceType].
  static final openingBalanceType =
      obx.QueryStringProperty<LedgerModel>(_entities[2].properties[4]);
}
